# IMPACT QC - MULTIQC CONFIG FILE

# Run only these modules
run_modules:
  - custom_content
  - custom_data
  - fastqc
  - fastp
  - picard
  - samtools
  - mosdepth
  - gatk
  - sexdeterrmine
  - somalier
  - fastq_screen
  - bcftools
  - vcftools
  - snpeff
  - vep

module_order:
  - fastqc:
      name: "FastQC (raw)"
      path_filters_exclude:
        - "*_val_*.zip"
  - fastp:
      name: "FastP (Read preprocessing)"
  - fastq_screen:
      name: "FastQ Screen"
  - picard:
      name: "GATK-PICARD tools"
      info: "Metrics generated either by GATK4 MarkDuplicates or EstimateLibraryComplexity (with --use_gatk_spark), GATK4 CollectInsertSizeMetrics, CollectHsMetrics and CollectTargetedPcrMetrics"
  - samtools:
      name: "Samtools Flagstat"
  - mosdepth:
      name: "Mosdepth"
  - gatk:
      name: "GATK4 BQSR"
  - sexdeterrmine:
      name: "Sex.DetERRmine"
  - somalier:
      name: "Somalier"
  - bcftools:
      name: "Bcftools"
  - vcftools:
      name: "Vcftools"
  - snpeff:
      name: "SNPeff"
  - vep:
      name: "VEP"

mosdepth_config:
  general_stats_coverage:
    - 1 
    - 10
    - 20
    - 30
    - 100

fastqscreen_simpleplot: true

#custom_data:
#  fastp_stats:
#    id: "fastp_stats"
#    section_name: "Fastp stats"
#    plot_type: "table"
#    pconfig:
#      id: "fastp_stats"
#      namespace: "Fastp stats"
#    headers:
#      N_SEQ_BASES_BEFORE:
#        description: "Number of sequenced bases before filtering"
#      N_SEQ_BASES_AFTER:
#        description: "Number of sequenced bases after filtering"
#      N_SEQ_BASES_Q30_BEFORE:
#        description: "Number of sequenced bases qith Q>30 before filtering"
#      N_SEQ_BASES_Q30_AFTER:
#        description: "Number of sequenced bases qith Q>30 after filtering"
#      N_READS_BEFORE:
#        description: "Number of reads before filtering"
#      N_READS_AFTER:
#        description: "Number of reads after filtering"
#      PCT_PASSED_READS:
#        description: "Percentage of reads that passed the filtering"
#      PCT_FAILED_READS: 
#        description: "Percentage of reads that failed the filtering"
#  bcftools_stats:
#    id: "bcftools_stats"
#    section_name: "Bcftools stats"
#    plot_type: "generalstats"
#    pconfig:
#      id: "bcftools_stats"
#      namespace: "Bcftools stats"
#    headers:
#     RATIO_HET-HOM: "Ratio of heterzygous/homozygous variants"
#     N_MULTIALLELIC_VARIANTS: "Number of multiallelic variants"
#     N_MULTIALLELIC_SNP_VARIANTS: "Number of multialleic SNP variants"
 

     #sp:
      #fastp_stats:
      #fn: "*.fastp_stats_mqc.tsv"
      #bcftools_stats:
      #fn: "*bcftools_stats_mqc.tsv"

### TEST
custom_data:
  my_gen_stats:
    id: "stats"
    section_name: "Stats"
    plot_type: 'generalstats'
    pconfig: 
      - N_SEQ_BASES_BEFORE: 
      - N_SEQ_BASES_AFTER:
      - N_SEQ_BASES_Q30_BEFORE:      
      - N_SEQ_BASES_Q30_AFTER:

sp:
  my_gen_stats:
    fn: "*_stats_mqc.tsv"
  

table_columns_visible:
  FastQC (raw):
    percent_duplicates: True
    percent_gc: True
    avg_sequence_length: True 
    median_sequence_length: True
    percent_fails: False
    total_sequences: True
  FastP (Read preprocessing):
    pct_duplication: False
    after_filtering_q30_rate: False
    after_filtering_q30_bases: False
    after_filtering_gc_content: True
    filtering_result_passed_filter_reads: False
    pct_surviving: False
      #GATK-PICARD tools/HsMetrics:
      #FOLD_ENRICHMENT: True
      #MEDIAN_TARGET_COVERAGE: False
      #PCT_TARGET_BASES_30X: False
      #GATK-PICARD tools/InsertSizeMetrics:
      #summed_median: True
      #summed_mean: True
      #GATK-PICARD tools/Mark Duplicates:
      #PERCENT_DUPLICATION: True
      #GATK-PICARD tools/TargetedPcrMetrics:
      #PCT_AMPLIFIED_BASES: True
  samtools/stats:
    error_rate: True
    non-primary_alignments: False
    reads_mapped: True
    reads_mapped_percent: True  
    reads_properly_paired_percent: True
    reads_MQ0_percent: False
    raw_total_sequences: False
  samtools/flagstat:
    flagstat_total: True
    mapped_passed: False
    mapped_passed_pct: False
  mosdepth:
    1_x_pc: True
    8_x_pc: False
    10_x_pc: True
    20_x_pc: True
    30_x_pc: True
    100_x_pc: True
    median_coverage: True
  Sex.DetERRmine:
    RateErrX: False
    RateErrY: False
    RateX: True
    RateY: True
  bcftools/stats:
    number_of_records: True
    number_of_SNPs: True
    number_of_indels: True
    tstv: True
    number_of_MNPs: False
    variations_hom: True
    variations_het: True

picard_config:
  HsMetrics_genstats_table_cols:
    - FOLD_ENRICHMENT
  HsMetrics_genstats_table_cols_hidden:
    - MEDIAN_TARGET_COVERAGE
    - PCT_TARGET_BASES_30X
  insertsize_genstats_table_cols:
    - summed_median
    - summed_mean
  markdups_genstats_table_cols:
    - PERCENT_DUPLICATION
  pcrmetrics_genstats_table_cols:
    - PCT_AMPLIFIED_BASES

table_columns_placement:
  FastQC (raw):
    percent_duplicates: 990
    percent_gc: 990
    avg_sequence_length: 990 
    median_sequence_length: 990
    percent_fails: 990
    total_sequences: 990
  FastP (Read preprocessing):
    pct_duplication: 1000
    after_filtering_q30_rate: 1000
    after_filtering_q30_bases: 1000
    filtering_result_passed_filter_reads: 1000
    pct_surviving: 1000
    after_filtering_gc_content: 1000
  #GATK-PICARD tools/HsMetrics:
  #  FOLD_ENRICHMENT: 1020
  #  MEDIAN_TARGET_COVERAGE: 1020
  #  PCT_TARGET_BASES_30X: 1020
  #GATK-PICARD tools/InsertSizeMetrics:
  #  summed_median: 1016
  #  summed_mean: 1016
  #GATK-PICARD tools/Mark Duplicates:
  #  PERCENT_DUPLICATION: 1021
  #GATK-PICARD tools/TargetedPcrMetrics:
  #  PCT_AMPLIFIED_BASES: 1021
  samtools/stats:
    error_rate: 1017
    non-primary_alignments: 1017
    reads_mapped: 1017
    reads_mapped_percent: 1017  
    reads_properly_paired_percent: 1017
    reads_MQ0_percent: 1017
    raw_total_sequences: 1017
  samtoolsflagstat:
    flagstat_total: 1017
    mapped_passed: 1017
    mapped_passed_pct: 1017
  mosdepth:
    1_x_pc: 1009
    8_x_pc: 1010
    10_x_pc: 1011
    20_x_pc: 1012
    30_x_pc: 1013
    100_x_pc: 1014
    median_coverage: 1015
  Sex.DetERRmine:
    RateErrX: 1025
    RateErrY: 1025
    RateX: 1026
    RateY: 1026
  bcftools:
    number_of_records: 1040
    number_of_SNPs: 1041
    number_of_indels: 1042
    tstv: 1050
    number_of_MNPs: 1060
    variations_hom: 1045
    variations_het: 1045
  bcftools_stats:
     RATIO_HET-HOM: 1064
     N_MULTIALLELIC_VARIANTS: 1065
     N_MULTIALLELIC_SNP_VARIANTS: 1066
  fastp_stats:
    N_SEQ_BASES_BEFORE: 1001
    N_SEQ_BASES_AFTER: 1002
    N_SEQ_BASES_Q30_BEFORE: 1003
    N_READS_BEFORE: 1005
    PCT_FAILED_READS: 1008    
