name: fastq-screen
description: Allows you to screen a library of sequences in FastQ format against a set of sequence databases so you can see if the composition of the library matches with what you expect
keywords:
  - quality control
  - fastq
  - mapping
  - genome
tools:
  - fastp:
      description: |
        Simple application which allows you to search a large sequence dataset against a panel of different genomes to determine from where the sequences in your data originate. It was built as a QC check for sequencing pipelines but may also have uses in metagenomics studies where mixed samples are expected.
      documentation: https://github.com/StevenWingett/FastQ-Screen
      doi: https://doi.org/10.12688/f1000research.15931.2
      licence: ["GPL-3.0"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information. Use 'single_end: true' to specify single ended or interleaved FASTQs. Use 'single_end: false' for paired-end reads.
        e.g. [ id:'test', single_end:false ]
  - reads:
      type: file
      description: |
        List of input FastQ files of size 1 and 2 for single-end and paired-end data,
        respectively. If you wish to run interleaved paired-end data,  supply as single-end data
        but with `--interleaved_in` in your `modules.conf`'s `ext.args` for the module.
  - fastq_screen_conf_db
      type: files
      description: |
        Configuration file for Fastq_Screen together with the different bowtie indexes files of the desired species.
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - html:
      type: file
      description: Results in HTML format
      pattern: "*.html"
  - png:
      type: file
      description: Plot reults png file
      pattern: "*.png"
  - txt:
      type: file
      description: Table results
      pattern: "*.txt"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@solcos"
