repository_type: pipeline
lint:
  actions_ci: False
  files_exist:
    - .github/workflows/awsfulltest.yml
    - conf/modules.config
  files_unchanged:
    - .gitignore
    - assets/nf-core-sarek_logo_light.png
    - docs/images/nf-core-sarek_logo_dark.png
    - docs/images/nf-core-sarek_logo_light.png
    - lib/NfcoreTemplate.groovy
    - lib/NfcoreSchema.groovy
  template_strings: False
