name: bcftoolscustom
description: Generates the heterozygous/homozygous ratio of the SNPs and extracts the DP and GQ from VCF files
keywords:
  - variant calling
  - heterozygous
  - homozygous
  - DP
  - GQ
  - VCF
tools:
  - stats:
      description: |
        Parses VCF or BCF and produces a text file with the values of heterozygous and homozygous SNPs and the ratio and another text file with the values of DP and GQ.
      homepage: http://samtools.github.io/bcftools/bcftools.html
      documentation: http://www.htslib.org/doc/bcftools.html
      doi: 10.1093/bioinformatics/btp352
      licence: ["MIT"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - vcf:
      type: file
      description: VCF input file
      pattern: "*.{vcf}"
  - tbi:
      type: file
      description: |
        The tab index for the VCF file to be inspected. Optional: only required when parameter regions is chosen.
      pattern: "*.tbi"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - ratio:
      type: file
      description: Text output file containing the ratio
      pattern: "*_{het-hom_ratio.txt}"
  - dp_gq_distribution:
      type: file
      description: Text output file containing DP and GQ
      pattern: "*_{dp_gq_distribution.txt}"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@solcos"
maintainers:
  - "@solcos"
