name: vcftoolscustom
description: A set of tools written in Perl and C++ for working with VCF files. This module computes GQ and strand bias (SB) distributions for the different variant callers. DeepVariant does not output SB.
keywords:
  - VCF
  - GQ
  - strand bias
  - distribution
tools:
  - vcftools:
      description: A set of tools written in Perl and C++ for working with VCF files. This package only contains the C++ libraries whereas the package perl-vcftools-vcf contains the perl libraries
      homepage: http://vcftools.sourceforge.net/
      documentation: http://vcftools.sourceforge.net/man_latest.html
      licence: ["LGPL"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - variant_file:
      type: file
      description: variant input file which can be vcf, vcf.gz, or bcf format.
  - bed:
      type: file
      description: bed file which can be used with different arguments in vcftools (optional)
  - diff_variant_file:
      type: file
      description: secondary variant file which can be used with the 'diff' suite of tools (optional)
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - distribution:
      type: file
      description: File containing GQ and SB distribution
      pattern: "*.{FORMAT,INFO}"
  - mqc_gq_distribution:
      type: file
      description: File containing the GQ distribution with MultiQC format
      pattern: "*_mqc.txt"
authors:
  - "@solcos"
maintainers:
  - "@solcos"
