name: "ngscat"
description: Assesses capture performance in terms of sensibility, specificity and uniformity of the coverage.
keywords:
  - performance
  - sensibility
  - specificity
  - uniformity
  - coverage
tools:
  - "ngscat":
      description: "Linux command-line application written in Python which facilitates a comprehensive evaluation of the performance of the capture step in targeted highthroughput sequencing experiments in terms of the Sensitivity, Specificity and Uniformity"
      homepage: "https://bio.tools/ngscat"
      documentation: "https://ngscat.clinbioinfosspa.es/_media/ngscat/download/manual_v0.1.pdf"
      tool_dev_url: "https://ngscat.clinbioinfosspa.es/_media/ngscat/download/manual_v0.1.pdf"
      doi: "10.1093/BIOINFORMATICS/BTU108"
      licence: "['GPL v3']"

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - bam:
      type: file
      description: BAM file (with header)
      pattern: "*.bam"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"



  - json:
      type: file
      description: JSON formatted table of relative coverages on the X and Y, with associated error bars.
      pattern: "*.json"
  - tsv:
      type: file
      description: TSV table of relative coverages on the X and Y, with associated error bars.
      pattern: "*.tsv"

authors:
  - "@solcos"
