name: "collectinsertsizemetrics"
description: Collect metrics about the insert size distribution of a paired-end library.
keywords:
  - metrics
  - alignment
  - insert
  - statistics
  - bam
tools:
  - gatk4:
      description: |
        Developed in the Data Sciences Platform at the Broad Institute, the toolkit offers a wide variety of tools
        with a primary focus on variant discovery and genotyping. Its powerful processing engine
        and high-performance computing features make it capable of taking on projects of any size.
      homepage: https://gatk.broadinstitute.org/hc/en-us
      documentation: https://gatk.broadinstitute.org/hc/en-us/articles/13832774634139-DepthOfCoverage-BETA-
      doi: 10.1158/1538-7445.AM2017-3590
      licence: ["Apache-2.0"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - bam:
      type: file
      description: BAM/CRAM/SAM file
      pattern: "*.{bam,cram,sam}"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - pdf:
      type: file
      description: Histogram plots of the insert size metrics computed by Picard
      pattern: "*.pdf"
  - metrics:
      type: file
      description: Values used by Picard to generate the insert size histograms
      pattern: "*.txt"
authors:
  - "@FerriolCalvet"
maintainers:
  - "@FerriolCalvet"
