name: "somalier"
description: Extract informative sites, evaluate relatedness, and perform quality-control on BAM/CRAM/BCF/VCF/GVCF.
keywords:
  - sex determination
  - genetic sex
  - relative coverage
  - relatedness
tools:
  - "somalier":
      description: "Extract informative sites, evaluate relatedness, and perform quality-control on BAM/CRAM/BCF/VCF/GVCF."
      homepage: "https://github.com/brentp/somalier"
      documentation: "https://github.com/brentp/somalier/README.md"
      tool_dev_url: "https://github.com/brentp/somalier"
      doi: "10.1186/s13073-020-00761-2"
      licence: "['MIT License']"

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - depth:
      type: file
      description: Cram file outputed from pre-processing
      pattern: "*"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - reports:
      type: file
      description: HTML formatted file.
      pattern: "*.html"
  - tsv:
      type: file
      description: Different TSV tables with all the information extracted.
      pattern: "*.tsv"

authors:
  - "@brentp"
